name: Terraform Deployment
on:
    push:
        branches:
            - main

jobs:
    terraform:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: latest
            
            - name: Azure CLI Login
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
            - name: Terraform Init
              run: terraform init
              working-directory: terraform

            - name: Terraform Validate
              run: terraform validate
              working-directory: terraform
            
            - name: Terraform Plan
              run: terraform plan
              working-directory: terraform
            
            - name: Terraform Apply
              run: terraform apply -auto-approve
              working-directory: terraform